In [200]:
import numpy as np
import pandas as  pd

In [201]:
movies=pd.read_csv('/content/tmdb_5000_moviesS.csv')
credits=pd.read_csv('/content/tmdb_5000_creditsS.csv')
movies.shape[0]

4803

In [202]:
credits.shape[0]

4803

In [203]:
movies.shape[0]

4803

In [204]:
credits.rename(columns={'movie_id':'id'},inplace=True)
credits.head()

,id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [205]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [206]:
credits['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

genres,id,keywords,title_x,cast,crew

In [207]:
movies=movies.merge(credits,how='inner',on='id')
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [208]:
movies.merge(credits,how='inner',on='id').shape

(4803, 26)

In [209]:
movies.shape

(4803, 23)

In [210]:
credits.shape

(4803, 4)

In [211]:
movies=movies[['genres','keywords','title_x','overview','cast','crew','id']]
movies

,genres,keywords,title_x,overview,cast,crew,id
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",19995
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",285
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",206647
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",49026
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",49529
...,...,...,...,...,...,...,...
4798,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de...",9367
4799,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de...",72766
4800,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de...",231617
4801,[],[],Shanghai Calling,When ambitious New York attorney Sam is sent t...,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",126186
4802,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",My Date with Drew,Ever since the second grade when he first saw ...,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de...",25975

In [212]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   genres    4803 non-null   object
 1   keywords  4803 non-null   object
 2   title_x   4803 non-null   object
 3   overview  4800 non-null   object
 4   cast      4803 non-null   object
 5   crew      4803 non-null   object
 6   id        4803 non-null   int64
dtypes: int64(1), object(6)
memory usage: 262.8+ KB

In [213]:
movies['overview'][1]

'Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems.'

'id'|title|tags

tags-->>overview + genre + keywords + cast + crew

In [214]:
movies['overview'].isnull().sum()

np.int64(3)

In [215]:
movies['genres'].isnull().sum()

np.int64(0)

In [216]:
movies['cast'].isnull().sum()

np.int64(0)

In [217]:
movies['crew'].isnull().sum()

np.int64(0)

In [218]:
movies['title_x'].isnull().sum()

np.int64(0)

In [219]:
movies['keywords'].isnull().sum()

np.int64(0)

In [220]:
movies.isnull().sum()

genres      0
keywords    0
title_x     0
overview    3
cast        0
crew        0
id          0
dtype: int64

In [221]:
movies.dropna(inplace=True)

/tmp/ipython-input-3786870272.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.dropna(inplace=True)

In [222]:
movies.isnull().sum()

genres      0
keywords    0
title_x     0
overview    0
cast        0
crew        0
id          0
dtype: int64

In [223]:
movies.duplicated().sum()

np.int64(0)

In [224]:
movies['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [225]:
import ast

# def convert(obj):
#     L = []
#     if isinstance(obj, list):
#         return obj
#     for i in ast.literal_eval(obj):
#         L.append(i['name'])
#     return L

In [226]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [227]:
movies['genres'].apply(convert)

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4798                        [Action, Crime, Thriller]
4799                                [Comedy, Romance]
4800               [Comedy, Drama, Romance, TV Movie]
4801                                               []
4802                                    [Documentary]
Name: genres, Length: 4800, dtype: object

In [228]:
movies['genres']=movies['genres'].apply(convert)
movies.head()

/tmp/ipython-input-2919212546.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres']=movies['genres'].apply(convert)

,genres,keywords,title_x,overview,cast,crew,id
0,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",19995
1,"[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",285
2,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",206647
3,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",49026
4,"[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",49529

In [229]:
movies['keywords'][1]

'[{"id": 270, "name": "ocean"}, {"id": 726, "name": "drug abuse"}, {"id": 911, "name": "exotic island"}, {"id": 1319, "name": "east india trading company"}, {"id": 2038, "name": "love of one\'s life"}, {"id": 2052, "name": "traitor"}, {"id": 2580, "name": "shipwreck"}, {"id": 2660, "name": "strong woman"}, {"id": 3799, "name": "ship"}, {"id": 5740, "name": "alliance"}, {"id": 5941, "name": "calypso"}, {"id": 6155, "name": "afterlife"}, {"id": 6211, "name": "fighter"}, {"id": 12988, "name": "pirate"}, {"id": 157186, "name": "swashbuckler"}, {"id": 179430, "name": "aftercreditsstinger"}]'

In [230]:
movies['keywords']=movies['keywords'].apply(convert)
movies.head()

/tmp/ipython-input-1255875170.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords']=movies['keywords'].apply(convert)

,genres,keywords,title_x,overview,cast,crew,id
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",19995
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",285
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",206647
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",49026
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",49529

In [231]:
movies['cast'][1]

'[{"cast_id": 4, "character": "Captain Jack Sparrow", "credit_id": "52fe4232c3a36847f800b50d", "gender": 2, "id": 85, "name": "Johnny Depp", "order": 0}, {"cast_id": 5, "character": "Will Turner", "credit_id": "52fe4232c3a36847f800b511", "gender": 2, "id": 114, "name": "Orlando Bloom", "order": 1}, {"cast_id": 6, "character": "Elizabeth Swann", "credit_id": "52fe4232c3a36847f800b515", "gender": 1, "id": 116, "name": "Keira Knightley", "order": 2}, {"cast_id": 12, "character": "William \\"Bootstrap Bill\\" Turner", "credit_id": "52fe4232c3a36847f800b52d", "gender": 2, "id": 1640, "name": "Stellan Skarsg\\u00e5rd", "order": 3}, {"cast_id": 10, "character": "Captain Sao Feng", "credit_id": "52fe4232c3a36847f800b525", "gender": 2, "id": 1619, "name": "Chow Yun-fat", "order": 4}, {"cast_id": 9, "character": "Captain Davy Jones", "credit_id": "52fe4232c3a36847f800b521", "gender": 2, "id": 2440, "name": "Bill Nighy", "order": 5}, {"cast_id": 7, "character": "Captain Hector Barbossa", "credit_id": "52fe4232c3a36847f800b519", "gender": 2, "id": 118, "name": "Geoffrey Rush", "order": 6}, {"cast_id": 14, "character": "Admiral James Norrington", "credit_id": "52fe4232c3a36847f800b535", "gender": 2, "id": 1709, "name": "Jack Davenport", "order": 7}, {"cast_id": 13, "character": "Joshamee Gibbs", "credit_id": "52fe4232c3a36847f800b531", "gender": 2, "id": 2449, "name": "Kevin McNally", "order": 8}, {"cast_id": 11, "character": "Lord Cutler Beckett", "credit_id": "52fe4232c3a36847f800b529", "gender": 2, "id": 2441, "name": "Tom Hollander", "order": 9}, {"cast_id": 19, "character": "Tia Dalma", "credit_id": "52fe4232c3a36847f800b549", "gender": 1, "id": 2038, "name": "Naomie Harris", "order": 10}, {"cast_id": 8, "character": "Governor Weatherby Swann", "credit_id": "52fe4232c3a36847f800b51d", "gender": 2, "id": 378, "name": "Jonathan Pryce", "order": 11}, {"cast_id": 37, "character": "Captain Teague Sparrow", "credit_id": "52fe4232c3a36847f800b5b3", "gender": 2, "id": 1430, "name": "Keith Richards", "order": 12}, {"cast_id": 16, "character": "Pintel", "credit_id": "52fe4232c3a36847f800b53d", "gender": 2, "id": 1710, "name": "Lee Arenberg", "order": 13}, {"cast_id": 15, "character": "Ragetti", "credit_id": "52fe4232c3a36847f800b539", "gender": 2, "id": 1711, "name": "Mackenzie Crook", "order": 14}, {"cast_id": 18, "character": "Lieutenant Theodore Groves", "credit_id": "52fe4232c3a36847f800b545", "gender": 2, "id": 4031, "name": "Greg Ellis", "order": 15}, {"cast_id": 55, "character": "Cotton", "credit_id": "57e28d2ec3a3681a01005b5c", "gender": 2, "id": 1715, "name": "David Bailie", "order": 16}, {"cast_id": 17, "character": "Marty", "credit_id": "52fe4232c3a36847f800b541", "gender": 2, "id": 4030, "name": "Martin Klebba", "order": 17}, {"cast_id": 57, "character": "Ian Mercer", "credit_id": "57e28d78c3a36808b900bf4f", "gender": 0, "id": 939, "name": "David Schofield", "order": 18}, {"cast_id": 62, "character": "Scarlett", "credit_id": "57e28ec5c3a3681a50005855", "gender": 1, "id": 2450, "name": "Lauren Maher", "order": 19}, {"cast_id": 63, "character": "Giselle", "credit_id": "57e28ed692514123f5005635", "gender": 1, "id": 2452, "name": "Vanessa Branch", "order": 20}, {"cast_id": 60, "character": "Mullroy", "credit_id": "57e28db2c3a3681a01005bc7", "gender": 2, "id": 1714, "name": "Angus Barnett", "order": 21}, {"cast_id": 59, "character": "Murtogg", "credit_id": "57e28da192514118f7006008", "gender": 0, "id": 1713, "name": "Giles New", "order": 22}, {"cast_id": 58, "character": "Tai Huang", "credit_id": "57e28d8ec3a3681a01005bab", "gender": 2, "id": 22075, "name": "Reggie Lee", "order": 23}, {"cast_id": 64, "character": "Henry Turner", "credit_id": "57e29119925141151100a6cc", "gender": 2, "id": 61259, "name": "Dominic Scott Kay", "order": 24}, {"cast_id": 39, "character": "Mistress Ching", "credit_id": "52fe4232c3a36847f800b5bd", "gender": 1, "id": 33500, "name": "Takayo Fischer", "order": 25}, {"cast_id": 40, "character": "Lieutenant Greitzer", "credit_id": "52fe4232c3a36847f800b5c1", "gender": 2, "id": 1224149, "name": "David Meunier", "order": 26}, {"cast_id": 49, "character": "Hadras", "credit_id": "56d1871c92514174680010cf", "gender": 2, "id": 429401, "name": "Ho-Kwan Tse", "order": 27}, {"cast_id": 56, "character": "Clacker", "credit_id": "57e28d4b92514125710055cb", "gender": 0, "id": 1123, "name": "Andy Beckwith", "order": 28}, {"cast_id": 51, "character": "Penrod", "credit_id": "56ec8c14c3a3682260003c53", "gender": 2, "id": 1056117, "name": "Peter Donald Badalamenti II", "order": 29}, {"cast_id": 61, "character": "Cotton\'s Parrot (voice)", "credit_id": "57e28dcc9251412463005678", "gender": 2, "id": 21700, "name": "Christopher S. Capp", "order": 30}, {"cast_id": 65, "character": "Captain Teague", "credit_id": "58bc2a37c3a368663003740b", "gender": 2, "id": 1430, "name": "Keith Richards", "order": 31}, {"cast_id": 66, "character": "Captain Jocard", "credit_id": "58bc2a8e925141609e03a179", "gender": 2, "id": 2603, "name": "Hakeem Kae-Kazim", "order": 32}, {"cast_id": 67, "character": "Captain Ammand", "credit_id": "58e2a21ac3a36872af00f9c2", "gender": 0, "id": 70577, "name": "Ghassan Massoud", "order": 33}]'

In [232]:
def convert3(obj):
    L = []
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L
#

In [233]:
movies['cast']=movies['cast'].apply(convert3)
movies

/tmp/ipython-input-2217777370.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast']=movies['cast'].apply(convert3)

,genres,keywords,title_x,overview,cast,crew,id
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",19995
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",285
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",206647
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",49026
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",49529
...,...,...,...,...,...,...,...
4798,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...",El Mariachi,El Mariachi just wants to play his guitar and ...,"[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de...",9367
4799,"[Comedy, Romance]",[],Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Edward Burns, Kerry Bishé, Marsha Dietlein]","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de...",72766
4800,"[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Eric Mabius, Kristin Booth, Crystal Lowe]","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de...",231617
4801,[],[],Shanghai Calling,When ambitious New York attorney Sam is sent t...,"[Daniel Henney, Eliza Coupe, Bill Paxton]","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",126186
4802,[Documentary],"[obsession, camcorder, crush, dream girl]",My Date with Drew,Ever since the second grade when he first saw ...,"[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de...",25975

In [234]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [235]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [236]:
movies['crew']=movies['crew'].apply(fetch_director)

movies

/tmp/ipython-input-2249970869.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew']=movies['crew'].apply(fetch_director)

,genres,keywords,title_x,overview,cast,crew,id
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],19995
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],285
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],206647
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],49026
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],49529
...,...,...,...,...,...,...,...
4798,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...",El Mariachi,El Mariachi just wants to play his guitar and ...,"[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez],9367
4799,"[Comedy, Romance]",[],Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Edward Burns, Kerry Bishé, Marsha Dietlein]",[Edward Burns],72766
4800,"[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Eric Mabius, Kristin Booth, Crystal Lowe]",[Scott Smith],231617
4801,[],[],Shanghai Calling,When ambitious New York attorney Sam is sent t...,"[Daniel Henney, Eliza Coupe, Bill Paxton]",[Daniel Hsia],126186
4802,[Documentary],"[obsession, camcorder, crush, dream girl]",My Date with Drew,Ever since the second grade when he first saw ...,"[Drew Barrymore, Brian Herzlinger, Corey Feldman]",[Brian Herzlinger],25975

In [237]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [238]:
movies['overview']=movies['overview'].apply(lambda x:x.split())
movies

/tmp/ipython-input-1630065153.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['overview']=movies['overview'].apply(lambda x:x.split())

,genres,keywords,title_x,overview,cast,crew,id
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],19995
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],285
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],206647
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],49026
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],49529
...,...,...,...,...,...,...,...
4798,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...",El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez],9367
4799,"[Comedy, Romance]",[],Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Edward Burns, Kerry Bishé, Marsha Dietlein]",[Edward Burns],72766
4800,"[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Eric Mabius, Kristin Booth, Crystal Lowe]",[Scott Smith],231617
4801,[],[],Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...","[Daniel Henney, Eliza Coupe, Bill Paxton]",[Daniel Hsia],126186
4802,[Documentary],"[obsession, camcorder, crush, dream girl]",My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...","[Drew Barrymore, Brian Herzlinger, Corey Feldman]",[Brian Herzlinger],25975

REMOVE THE SPACE OF WORDS

In [239]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])
movies

/tmp/ipython-input-1313680971.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
/tmp/ipython-input-1313680971.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
/tmp/ipython-input-1313680971.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
/tmp/ipython-input-1313680971.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

,genres,keywords,title_x,overview,cast,crew,id
0,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],19995
1,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],285
2,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],206647
3,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],49026
4,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],49529
...,...,...,...,...,...,...,...
4798,"[Action, Crime, Thriller]","[unitedstates–mexicobarrier, legs, arms, paper...",El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez],9367
4799,"[Comedy, Romance]",[],Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[EdwardBurns, KerryBishé, MarshaDietlein]",[EdwardBurns],72766
4800,"[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith],231617
4801,[],[],Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...","[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia],126186
4802,[Documentary],"[obsession, camcorder, crush, dreamgirl]",My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[BrianHerzlinger],25975

In [240]:
movies['tags']=movies['genres']+movies['keywords']+movies['overview']+movies['cast']+movies['crew']
movies

/tmp/ipython-input-3316853062.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags']=movies['genres']+movies['keywords']+movies['overview']+movies['cast']+movies['crew']

,genres,keywords,title_x,overview,cast,crew,id,tags
0,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],19995,"[Action, Adventure, Fantasy, ScienceFiction, c..."
1,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],285,"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],206647,"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],49026,"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],49529,"[Action, Adventure, ScienceFiction, basedonnov..."
...,...,...,...,...,...,...,...,...
4798,"[Action, Crime, Thriller]","[unitedstates–mexicobarrier, legs, arms, paper...",El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez],9367,"[Action, Crime, Thriller, unitedstates–mexicob..."
4799,"[Comedy, Romance]",[],Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[EdwardBurns, KerryBishé, MarshaDietlein]",[EdwardBurns],72766,"[Comedy, Romance, A, newlywed, couple's, honey..."
4800,"[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith],231617,"[Comedy, Drama, Romance, TVMovie, date, loveat..."
4801,[],[],Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...","[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia],126186,"[When, ambitious, New, York, attorney, Sam, is..."
4802,[Documentary],"[obsession, camcorder, crush, dreamgirl]",My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[BrianHerzlinger],25975,"[Documentary, obsession, camcorder, crush, dre..."

In [241]:
movies['tags'][0]

['Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'JamesCameron']

In [242]:
new_df=movies[['id','title_x','tags']]
new_df

,id,title_x,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction, c..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,206647,Spectre,"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction, basedonnov..."
...,...,...,...
4798,9367,El Mariachi,"[Action, Crime, Thriller, unitedstates–mexicob..."
4799,72766,Newlyweds,"[Comedy, Romance, A, newlywed, couple's, honey..."
4800,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TVMovie, date, loveat..."
4801,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4802,25975,My Date with Drew,"[Documentary, obsession, camcorder, crush, dre..."

In [243]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))
new_df

/tmp/ipython-input-326038826.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

,id,title_x,tags
0,19995,Avatar,Action Adventure Fantasy ScienceFiction cultur...
1,285,Pirates of the Caribbean: At World's End,Adventure Fantasy Action ocean drugabuse exoti...
2,206647,Spectre,Action Adventure Crime spy basedonnovel secret...
3,49026,The Dark Knight Rises,Action Crime Drama Thriller dccomics crimefigh...
4,49529,John Carter,Action Adventure ScienceFiction basedonnovel m...
...,...,...,...
4798,9367,El Mariachi,Action Crime Thriller unitedstates–mexicobarri...
4799,72766,Newlyweds,Comedy Romance A newlywed couple's honeymoon i...
4800,231617,"Signed, Sealed, Delivered",Comedy Drama Romance TVMovie date loveatfirsts...
4801,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4802,25975,My Date with Drew,Documentary obsession camcorder crush dreamgir...

In [244]:
new_df['tags'][0]

'Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

CONVERT ALL TAGS IN SAMLL LETTERS

In [245]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())
new_df

/tmp/ipython-input-2565169282.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

,id,title_x,tags
0,19995,Avatar,action adventure fantasy sciencefiction cultur...
1,285,Pirates of the Caribbean: At World's End,adventure fantasy action ocean drugabuse exoti...
2,206647,Spectre,action adventure crime spy basedonnovel secret...
3,49026,The Dark Knight Rises,action crime drama thriller dccomics crimefigh...
4,49529,John Carter,action adventure sciencefiction basedonnovel m...
...,...,...,...
4798,9367,El Mariachi,action crime thriller unitedstates–mexicobarri...
4799,72766,Newlyweds,comedy romance a newlywed couple's honeymoon i...
4800,231617,"Signed, Sealed, Delivered",comedy drama romance tvmovie date loveatfirsts...
4801,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4802,25975,My Date with Drew,documentary obsession camcorder crush dreamgir...

In [246]:
new_df['tags'][0]

'action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. samworthington zoesaldana sigourneyweaver jamescameron'

In [247]:
new_df['tags'][1]

"adventure fantasy action ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. johnnydepp orlandobloom keiraknightley goreverbinski"

MAKING SIMILAR WORDS IN TO A SINGLE WORD (EXA--LOVED->LOVE,ACTIVITIES->ACTIVITY)

In [248]:
import nltk

In [249]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [250]:
def stem(text):
  y=[]
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)

In [251]:
stem(new_df['tags'][1])

"adventur fantasi action ocean drugabus exoticisland eastindiatradingcompani loveofone'slif traitor shipwreck strongwoman ship allianc calypso afterlif fighter pirat swashbuckl aftercreditssting captain barbossa, long believ to be dead, ha come back to life and is head to the edg of the earth with will turner and elizabeth swann. but noth is quit as it seems. johnnydepp orlandobloom keiraknightley goreverbinski"

In [252]:
new_df['tags']=new_df['tags'].apply(stem)
new_df

/tmp/ipython-input-2470178573.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

,id,title_x,tags
0,19995,Avatar,action adventur fantasi sciencefict culturecla...
1,285,Pirates of the Caribbean: At World's End,adventur fantasi action ocean drugabus exotici...
2,206647,Spectre,action adventur crime spi basedonnovel secreta...
3,49026,The Dark Knight Rises,action crime drama thriller dccomic crimefight...
4,49529,John Carter,action adventur sciencefict basedonnovel mar m...
...,...,...,...
4798,9367,El Mariachi,action crime thriller unitedstates–mexicobarri...
4799,72766,Newlyweds,comedi romanc a newlyw couple' honeymoon is up...
4800,231617,"Signed, Sealed, Delivered",comedi drama romanc tvmovi date loveatfirstsig...
4801,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4802,25975,My Date with Drew,documentari obsess camcord crush dreamgirl eve...

WE HAVE TO FIND THE  SIMILARITIES BETWEEN THE TAGS SO WE ARE USING THE VECTORIZATION TECHNIC AND CONVERTING TEXT INTO VECTORS

BAG OF WORDS TECHNIC OF TEXT VECTORIZARION

In [253]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [254]:
vectors=cv.fit_transform(new_df['tags']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [255]:
cv.fit_transform(new_df['tags']).toarray().shape

(4800, 5000)

In [256]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [257]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [258]:
for word in cv.get_feature_names_out():
    print(word)

000
007
10
100
11
12
13
14
15
16
17
17th
18
18th
18thcenturi
19
1910
1920
1930
1940
1944
1950
1950s
1960
1960s
1970
1970s
1971
1974
1976
1980
1985
1990
1999
19th
19thcenturi
20
200
2003
2009
20th
21st
23
24
25
30
300
3d
40
50
500
60
70
80
aaron
aaroneckhart
abandon
abduct
abigailbreslin
abil
abl
aboard
abov
abus
academ
academi
accept
access
accid
accident
acclaim
accompani
accomplish
account
accus
ace
achiev
acquaint
act
action
actionhero
activ
activist
activities
actor
actress
actual
ad
adam
adamsandl
adamshankman
adapt
add
addict
adjust
admir
admit
adolesc
adopt
ador
adrienbrodi
adult
adultanim
adulteri
adulthood
advanc
adventur
adventure
adventures
advertis
advic
advis
affair
affect
afghanistan
africa
african
africanamerican
aftercreditssting
afterlif
aftermath
ag
age
agediffer
agenc
agency
agenda
agent
agents
aggress
ago
agre
ahead
aid
aidanquinn
ail
aim
air
airplan
airplanecrash
airport
aka
al
alabama
alan
alaska
albert
alcatraz
alcohol
alecbaldwin
alex
alexkendrick
alfredhitchcock
alfredmolina
ali
alic
alice
alien
alieninvas
alienlife
alienplanet
aliens
alik
aliv
alive
allen
alli
allianc
allow
alon
alongsid
alpacino
alpha
alreadi
alter
altern
alway
alyssa
alzheimer
amanda
amandapeet
amandaseyfri
amateur
amaz
amazon
ambassador
ambit
ambiti
ambul
ambush
america
american
americanabroad
americancivilwar
americanfootbal
americanfootballplay
amid
amidst
amnesia
amp
amsterdam
amus
amusementpark
amy
amyadam
amysmart
ana
anakin
analyst
anarchiccomedi
ancient
ancientrom
ancientworld
anderson
andi
andiemacdowel
andrew
android
andy
andygarcía
angel
angela
angelabassett
angeles
angelinajoli
anger
angle
angri
ani
anim
animalattack
animalhorror
animals
anjelicahuston
ann
anna
annafari
annehathaway
annemoss
annetteben
anni
annie
anniversari
announc
annual
anonym
anoth
answer
ant
antholog
anthoni
anthonyanderson
anthonyhopkin
anthonymacki
anthropomorph
anti
antic
antihero
antiqu
antoinefuqua
antoniobandera
antonyelchin
anyon
anyth
apart
apartheid
apartment
ape
apocalyps
apocalypse
apocalypt
appar
appear
appl
apple
appoint
appreci
apprentic
approach
april
aquarium
arab
arch
archaeologist
archeolog
architect
arctic
area
aren
arena
argument
aris
aristocrat
arm
armi
armor
armsdeal
army
arnold
arnoldschwarzenegg
arrang
arrangedmarriag
arrest
arriv
arrog
art
arthur
artifact
artifici
artificialintellig
artist
ash
ashley
ashleyjudd
ashtonkutch
asia
asian
asid
ask
aspect
aspir
assassin
assault
assembl
assign
assist
assistant
associ
assum
asteroid
astronaut
asylum
atheist
athlet
atom
atomicbomb
attack
attacks
attempt
attempttoescap
attend
attent
attic
attitud
attorney
attract
auction
audienc
audit
august
aunt
austin
australia
australian
author
autism
auto
automobilerac
aveng
averag
avoid
await
awak
awaken
awar
award
away
awkward
awri
awry
ax
babe
babi
baby
bachelor
backdrop
background
backpack
bad
bag
bahama
bail
balanc
ball
ballet
balloon
baltimor
ban
band
bandit
bangkok
banish
bank
banker
bankrobb
bankrobberi
bar
barbrastreisand
bare
bargain
barn
barney
baron
barri
barrylevinson
barrysonnenfeld
bas
base
basebal
basedoncomicbook
basedongraphicnovel
basedonnovel
basedonplay
basedonstagemus
basedontrueev
basedontruestori
basedontvseri
basedonvideogam
basedonyoungadultnovel
basement
basketbal
basketball
bat
batman
battl
battle
battlefield
bay
beach
beam
bear
beard
beast
beat
beauti
beautiful
beautifulwoman
beauty
becam
becaus
becki
becom
becominganadult
bed
bedroom
bee
beer
befor
befriend
began
begin
begins
behavior
belief
believ
bell
bella
belong
belov
ben
benaffleck
bend
beneath
benefit
benfost
beniciodeltoro
benjamin
benjaminbratt
benkingsley
bennett
benstil
bent
berlin
best
bestfriend
bestfriendsinlov
bet
beth
betray
bettemidl
better
betti
beverli
bibl
bid
big
bigger
biggest
bike
biker
bikini
billhad
billi
billionair
billmurray
billnighi
billpaxton
billpullman
billybobthornton
billycrudup
billycryst
biographi
biolog
bird
birth
birthday
bisexu
bishop
bit
bite
bitter
bizarr
black
blackmag
blackmail
blackpeopl
blacksmith
blade
blame
blend
blind
bliss
blizzard
block
blond
blood
bloodi
bloodsplatt
bloodthirsti
blow
blue
board
boardingschool
boat
bob
bobbi
bobbyfarrelli
bobhoskin
bodi
body
bodyguard
bold
bollywood
bomb
bond
bone
book
border
bore
boredom
born
boss
boston
botch
bound
boundari
bounti
bountyhunt
bout
box
boxer
boy
boyfriend
boys
bradleycoop
bradpitt
brain
brainwash
brand
brandon
brave
braveri
brazil
brazilian
break
breakdown
breakup
breast
breath
breed
brendanfras
brendangleeson
brent
brettratn
brian
briandepalma
bride
bridesmaid
bridg
brief
brielarson
brien
bright
brilliant
bring
brink
britain
british
britishsecretservic
brittanymurphi
broadcast
broadway
broke
broken
broker
bronx
brook
brooklyn
broom
brothel
brother
brotherbrotherrelationship
brothers
brothersisterrelationship
brought
brown
bruce
brucegreenwood
brucewilli
brutal
bryansing
bu
buck
bud
buddi
buddy
buddycomedi
buddycop
budget
build
building
built
bullet
bulli
bumbl
bunch
bunker
bunni
burglar
buri
burn
bush
busi
business
businessman
bust
butcher
butler
butt
button
buy
buzz
cabin
caesar
cage
cairo
cal
california
calvin
camcord
came
camera
cameraman
camerondiaz
camp
campaign
campbell
campu
canada
canadian
cancer
candi
candid
canin
cannib
canuxploit
capabl
caper
capit
capt
captain
captiv
captur
capture
car
caraccid
carchas
carcrash
card
care
career
carefre
caretak
careymulligan
caribbean
carjourney
carl
carlagugino
carmen
carol
carolina
carrac
carri
carrie
cartel
carter
cartoon
caryelw
case
caseyaffleck
cash
casino
cast
castl
cat
cataclysm
catastroph
catch
cateblanchett
catherinedeneuv
catherinekeen
catherinezeta
cathol
catholic
cattl
caught
caus
cavalri
cave
cavemen
celebr
celebration
cell
cellphon
cemeteri
center
centr
central
centuri
centuries
century
ceo
certain
chad
chain
chainsaw
challeng
chamber
champion
championship
chanc
chance
chang
change
changed
changes
channingtatum
chao
chaos
chaotic
chapter
charact
character
characters
charg
charismat
charl
charli
charlie
charliesheen
charlizetheron
charm
chart
chase
chauffeur
chazzpalminteri
cheat
check
cheerlead
chef
chemic
cher
chevychas
chicago
chicken
chief
child
childabus
childhero
childhood
childprodigi
children
chill
chimp
china
chines
chip
chipmunk
chiwetelejiofor
chloe
chloëgracemoretz
chloësevigni
chocol
choic
choice
choos
chosen
chowyun
chri
chriscolumbu
chriscoop
chrisevan
chrishemsworth
chrisklein
chrispin
chrisrock
christ
christian
christianbal
christianslat
christin
christinaappleg
christinaricci
christma
christmas
christmasparti
christmastre
christoph
christopherlambert
christopherlloyd
christophernolan
christopherplumm
christopherwalken
christophwaltz
chrisweitz
chronicl
chuck
church
cia
ciaránhind
cigarettesmok
cillianmurphi
cinema
circl
circu
circuit
circumst
citi
citizen
city
civil
civilian
civilwar
claim
clair
clairedan
claireforlani
clan
clark
clash
class
classdiffer
classic
classmat
classroom
claudevandamm
clay
clean
clear
clerk
clever
client
clients
cliff
climat
climb
clinteastwood
cliveowen
clock
clone
close
closer
cloud
clown
club
clue
clueless
clutch
coach
coast
cocain
code
coffin
cohen
col
cold
coldwar
cole
colin
colinfarrel
colinfirth
collaps
colleagu
collect
collector
colleg
college
collid
collis
colombia
colonel
coloni
color
colorado
coma
combat
combin
come
comeback
comed
comedi
comedian
comedy
comet
comfort
comic
coming
comingofag
comingout
command
commando
commerci
commiss
commit
common
commun
communist
community
compani
companion
company
compet
competit
competition
complet
complex
complic
compos
compuls
comput
computerviru
conan
concern
concert
concoct
condit
condition
conduct
confeder
confess
confid
confin
conflict
confront
confus
congress
conman
connect
connecticut
connel
connor
conquer
consequ
consequences
conserv
consid
conspir
conspiraci
conspiracy
constant
constantli
construct
consum
contact
contain
contemporari
contend
content
contest
continu
contract
contractor
control
controversi
convent
converg
convers
convict
convinc
cook
cool
cooper
cop
cope
cops
core
corner
corp
corpor
corporation
corps
corrupt
cost
costum
couldn
counselor
count
countess
countless
countri
country
countryhous
countrymus
countrysid
coup
coupl
couple
courag
cours
court
courtcas
courteneycox
courtroom
cousin
cover
covert
covet
cow
cowardli
cowboy
crab
crack
craft
craig
crane
crash
crave
crazi
creat
creation
creativ
creator
creatur
creature
creatures
credit
creepi
crew
cri
crime
crimefight
crimes
crimin
criminal
criminals
crisi
crisis
critic
crocodil
crook
cross
crowd
crown
cruel
cruelti
cruis
crusad
crush
crystal
cuba
cubagoodingjr
culmin
cult
cultfilm
cultur
culture
cultureclash
cun
cup
cure
current
curs
curse
curtishanson
custodi
custom
cut
cuttingthecord
cyberpunk
cyborg
cynic
dad
daili
dakotafan
dale
damag
damon
dan
danaykroyd
danc
dancer
danger
daniel
danielcraig
danielday
danielradcliff
danni
danny
dannyboyl
dannydevito
dannyglov
dare
dark
darkcomedi
darkest
darkness
darylhannah
dash
date
daughter
daughters
dave
davi
david
davidarquett
davidcronenberg
davidduchovni
davidfinch
davidgordongreen
davidmors
davido
davidschwimm
davidspad
davidthewli
dawn
daxshepard
day
daydream
days
dc
dccomic
dea
dead
deadli
deadliest
deaf
deal
dealer
dean
death
deathofafriend
deathoffath
deathpenalti
debt
debut
decad
decapit
deceas
deceit
decept
decid
decis
declar
dedic
deed
deep
deeper
deepli
defeat
defend
defens
defi
defin
delight
deliv
deliveri
delus
demand
demimoor
demon
demonicpossess
demons
deni
deniserichard
denmark
denni
dennisdugan
dennishopp
dennisquaid
dentist
denzelwashington
depart
depend
depict
depress
depth
deputi
derang
derek
derekluk
descend
describ
desert
design
desir
desk
desol
despair
desper
despit
destin
destini
destiny
destroy
destroyed
destruct
destruction
detect
detective
determin
detroit
devast
develop
devic
devil
deviou
devis
devot
diabol
diagnos
dialogu
diamond
dian
dianekeaton
dianekrug
dianelan
diari
dick
dictat
did
didn
die
died
diego
dies
differ
different
difficult
difficulti
dig
dilemma
diner
dinner
dinosaur
diplomat
dire
direct
director
dirt
dirti
dirtycop
disabl
disappear
disappears
disast
disaster
disastr
discov
discoveri
diseas
disease
disfigur
disgrac
disguis
dishonesti
disillus
disney
disord
dispatch
disrupt
distant
district
distrust
disturb
ditch
diva
dive
divid
divis
divorc
divorce
dj
dna
doc
doctor
document
documentari
dodg
doe
doesn
dog
doll
dollar
dolphin
dolphlundgren
domest
domin
don
donaldpetri
donaldsutherland
doncheadl
donnel
doom
doomsday
door
doorstep
doppelgang
dorothi
doubl
double
doublecross
doublelif
doubt
doug
dougliman
dr
dracula
drag
dragon
drama
dramat
draw
drawn
dread
dream
dreams
dress
drew
drewbarrymor
drift
drifter
drink
drive
driven
driver
drone
drop
drown
drug
drugabus
drugaddict
drugdeal
druglord
drugs
drugsmuggl
drugtraff
drugus
drunk
drunken
du
dualident
dub
duck
dude
duel
duke
dump
duo
dure
duringcreditssting
dustinhoffman
dutch
duti
dwarv
dwaynejohnson
dyinganddeath
dylan
dynam
dynasti
dysfunct
dysfunctionalfamili
dystopia
dystopicfutur
eager
earli
earlier
earn
earth
earthquak
easi
easili
east
eat
eccentr
econom
economi
eddi
eddiegriffin
eddiemurphi
edg
edgar
edharri
editor
educ
edward
edwardburn
edwardnorton
edwardzwick
effect
effort
egg
ego
egypt
egyptian
el
elabor
elderli
elect
element
eleph
elev
eliaskotea
elijahwood
elimin
elisabethshu
elit
elite
elizabeth
elizabethbank
ella
ellenburstyn
ellenpag
elli
elliot
elliott
els
elud
elus
elv
elvi
embark
embassi
embroil
emerg
emigr
emilehirsch
emili
emilyblunt
emilymortim
emilywatson
emma
emmarobert
emmaston
emmathompson
emmawatson
emot
emperor
empir
empire
employ
employe
employer
enabl
enchant
encount
encourag
end
endless
endoftheworld
endur
enemi
enemies
enemy
energi
enforc
engag
engin
england
english
enigmat
enjoy
enlist
enorm
enrol
ensemblecast
ensu
ensues
ensur
entangl
enter
enterpris
entertain
enthusiast
entir
entiti
environ
environment
epic
epidem
episod
equal
era
eric
ericbana
erin
ernest
erotic
erupt
escap
escapad
escape
escapefromprison
escort
especi
espionag
establish
estat
estrang
etern
ethan
ethanhawk
ethic
eugenelevi
europ
european
eva
evacu
evad
evamend
evanrachelwood
eve
event
events
eventu
eventually
everi
everybodi
everyday
everyon
everyth
evid
evil
evolut
evolv
ewanmcgregor
ex
exact
exactli
exam
examin
exchang
excit
exclus
execut
exercis
exhibit
exil
exist
existence
existenti
exorc
exot
exoticisland
expect
expected
expedit
experi
experienc
experience
experiment
expert
explain
explod
exploit
explor
explos
expos
extend
extra
extramaritalaffair
extraordinari
extraterrestri
extraterrestrialtechnolog
extrem
extremeviol
eye
eyes
fabl
fac
face
facil
fact
faction
factori
fade
fail
fairi
fairytal
faith
fake
falcon
fall
fallen
fallinginlov
fals
falseident
falselyaccus
fame
famili
families
family
familyconflict
familyrelationship
famkejanssen
famou
famous
fan
fanat
fangvamp
fans
fantasi
fantast
fantasyworld
far
farewel
farm
farmer
fascin
fashion
fast
faster
fat
fatal
fate
father
fatherdaughterrelationship
fathersonrelationship
favor
favorit
fbi
fbiagent
fear
fearless
fearsom
featur
fed
feder
feed
feel
feet
fellow
femal
female
femalecorps
femalefriendship
femalenud
femaleprotagonist
fend
festiv
festival
fetish
feud
fi
fiance
fiancé
fiction
fictionalplac
field
fierc
fifth
fight
fighter
figur
fil
file
film
filmdirector
filmmak
filmproduc
films
final
finale
financ
financi
fine
finish
finn
firemen
firework
firm
firsttim
fish
fisherman
fishoutofwat
fistfight
fit
fix
flame
flash
flashback
flat
fledgl
flee
flesh
fli
flight
fling
flint
flirt
flood
florida
florist
flower
flyingsauc
focu
focus
foe
foil
foley
folk
follow
food
foot
footag
footbal
footchas
forbidden
forbiddenlov
forc
force
forces
ford
foreign
forest
forestwhitak
forev
forever
forg
forget
forgiv
form
formid
formula
fort
fortun
fortune
fortunetel
forward
foster
fought
foundfootag
fourth
fox
frame
franc
france
francisco
francisfordcoppola
frank
frankcoraci
frankenstein
franki
frankoz
frantic
fratern
fraud
freak
fred
freddi
freddieprinzejr
free
freedom
freeman
freez
french
frequent
fresh
freshman
friend
friendli
friends
friendship
frighten
frog
fromragstorich
frontier
frozen
frustrat
fu
fuel
fugit
fulfil
fulli
fun
fund
funer
funeral
furiou
futur
future
futurist
fword
ga
gabriel
gabrielbyrn
gadget
gaelgarcíabern
gain
galaxi
galaxy
gambl
gambler
game
games
gandhi
gang
gangs
gangster
gangsterboss
gangwar
garag
garden
garfield
gari
garrymarshal
garygray
garyoldman
garysinis
gasstat
gate
gather
gave
gay
gayinterest
gayrelationship
genehackman
gener
general
generation
genet
geniu
genius
gentl
geoffreyrush
georg
george
georgea
georgeclooney
georgemil
georgia
gerardbutl
german
germani
germany
getaway
ghetto
ghost
giant
giantrobot
gift
gig
girl
girlfriend
girls
given
glamor
glass
glennclos
global
globe
glori
goal
god
goe
gold
golden
golf
gone
good
goodvsevil
gordon
gore
goreverbinski
gorgeou
gorilla
gossip
got
gotham
gothamc
gotten
govern
government
governor
grace
grad
grade
gradual
graduat
grand
grandfath
grandfather
grandmoth
grandmother
grant
graphic
grasp
grave
great
greater
greatest
greec
greed
greedi
greek
green
greg
gregkinnear
gregorypeck
grew
grief
griev
griffin
grim
grip
grisli
ground
group
groupoffriend
grow
growingup
grown
gruesom
gu
guard
guardian
guerrilla
guest
guid
guilt
guitar
gun
gunfight
gunman
gunsling
guru
gusvans
guy
guypearc
guyritchi
guys
gwynethpaltrow
gym
gypsi
ha
hack
hacker
hair
haleyjoelos
half
hall
halleberri
halloween
hallucin
han
hand
handl
hands
handsom
handtohandcombat
hang
hangov
hannah
hansel
hapless
happen
happens
happi
happili
happiness
happy
hara
harass
harbor
hard
harder
harlem
harmoni
harold
haroldrami
harri
harriet
harrison
harrisonford
harrow
harry
harsh
hart
harvard
harvey
harveykeitel
hasn
hatch
hate
hatr
haunt
hauntedhous
haven
havoc
hawaii
haydenchristensen
haze
head
headlin
heal
health
hear
heard
heart
heartattack
heartbreak
heat
heather
heathergraham
heathledg
heaven
heavi
heavili
heavymet
height
heir
heiress
heist
held
helen
helenabonhamcart
helenhunt
helenmirren
helicopt
hell
help
henchmen
henri
hero
heroes
heroic
heroin
heroism
hi
hidden
hiddencamera
hide
high
higher
highest
highland
highli
highschool
highschoolsport
highschoolstud
highway
hijack
hike
hilari
hilaryduff
hilaryswank
hill
himalaya
hip
hippi
hire
histor
histori
historicalfigur
history
hit
hitch
hitchhik
hitman
ho
hobbit
hockey
hold
hole
holi
holiday
holli
hollywood
home
homeinvas
homeland
homeless
homelessperson
hometown
homicid
homophobia
homosexu
honey
honeymoon
hong
hongkong
honor
hood
hoodlum
hook
hop
hope
hopedavi
hopelessli
hord
horribl
horrif
horrifi
horror
hors
horsebackrid
horserac
hospit
hospital
host
hostag
hostage
hostil
hot
hotel
hotelroom
hotshot
hour
hous
house
household
housewif
howard
howev
hud
huge
hugh
hughgrant
hughjackman
human
humananimalrelationship
humanity
humankind
humans
humili
humor
hundr
hunger
hungri
hunt
hunter
hunters
hurrican
hurt
husband
hustler
hypnosi
hypnot
hyster
ianmckellen
ice
icecub
icon
idea
ideal
idealist
ident
identity
idol
idyl
ignit
ignor
ii
iii
ill
illeg
illegaldrug
illegalimmigr
illegalprostitut
illness
illus
illustr
imag
imagin
imaginari
imagined
imax
immedi
immens
immigr
immort
impact
imperi
imperson
implic
import
imposs
impostor
impress
imprison
inadvert
incest
incid
includ
incompet
increas
increasingli
incred
independ
independentfilm
indi
india
indian
indiana
indianlead
individu
industri
industry
inevit
inexplic
infam
infant
infect
infidel
infiltr
influenc
inform
inhabit
inherit
initi
inject
injur
injuri
inmat
inner
innoc
insan
insecur
insid
insight
insist
insomnia
inspector
inspir
instal
instant
instantli
instead
instinct
institut
institution
instructor
insur
insurg
intellig
intend
intens
intent
intergalact
intern
internet
interpret
interrog
interspeciesrom
intertwin
interview
intim
intoler
intrigu
introduc
invad
invas
invent
inventor
invest
investig
investigate
invis
invit
involv
iowa
ira
iran
iranian
iraq
iraqwar
ireland
irish
iron
islam
island
isn
isol
isra
israel
issu
itali
italian
ivanreitman
jack
jackass
jackblack
jacki
jackiechan
jacknicholson
jackson
jacob
jadapinkettsmith
jade
jail
jake
jakegyllenha
jamaica
jame
james
jamescaan
jamescameron
jamesfranco
jamesivori
jamesmangold
jamesmarsden
jamesmcavoy
jameswan
jameswood
jami
jamie
jamiefoxx
jamieleecurti
jan
jane
janitor
japan
japanes
jaredleto
jason
jasonbateman
jasonbigg
jasonle
jasonschwartzman
jasonsegel
jasonstatham
javierbardem
jay
jaychandrasekhar
jayroach
jazz
jealousi
jean
jeanreno
jedi
jeff
jeffbridg
jeffdaniel
jeffgoldblum
jeffreywright
jennif
jenniferaniston
jenniferconnelli
jennifergarn
jenniferjasonleigh
jenniferlawr
jenniferlopez
jenniferlovehewitt
jeremyiron
jeremyrenn
jerri
jersey
jerusalem
jess
jessebradford
jesseeisenberg
jessica
jessicaalba
jessicabiel
jessicachastain
jesu
jesus
jesuschrist
jetli
jew
jewel
jewish
jigsaw
jill
jim
jimbroadb
jimcarrey
jimcaviezel
jimmi
jimmy
jin
joanallen
joancusack
joaquinphoenix
job
jobinterview
jock
jodiefost
joe
joel
joelcoen
joeledgerton
joelschumach
joepesci
joey
john
johnc
johncarpent
johncusack
johngoodman
johnhurt
johnkrasinski
johnleguizamo
johnmalkovich
johnmctiernan
johnni
johnny
johnnydepp
johnnyknoxvil
johnsingleton
johnson
johntravolta
johnturturro
johnwoo
join
jon
jonahhil
jonathan
jonathanfrak
jonathanrhysmey
jone
jones
jonfavreau
jonturteltaub
jonvoight
jordan
joseph
josephgordon
josh
joshbrolin
joshhartnett
joshhutcherson
journal
journalist
journey
joy
jr
juan
judelaw
judg
judidench
juli
julia
julian
juliannemoor
juliarobert
juliastil
julie
jump
jungl
jungle
junior
junki
just
justic
justice
justinlong
justintimberlak
kansa
karat
karen
karlurban
kat
kate
katebeckinsal
katebosworth
katehudson
katemara
katewinslet
katherin
katherineheigl
kathi
kathyb
kati
katieholm
katniss
kay
keanureev
keiraknightley
kelli
kelly
kellypreston
ken
kennethbranagh
kermit
kevin
kevinbacon
kevincostn
kevinhart
kevinjam
kevinklin
kevinsmith
kevinspacey
key
kgb
khan
kick
kid
kidnap
kidnapp
kidnapped
kids
kidsandfamili
kiefersutherland
kill
killed
killer
killerrobot
killers
kim
kimbasing
kind
king
kingdom
kingpin
kirk
kirstendunst
kiss
kit
kitchen
knew
knife
knight
knit
knock
know
knowledg

In [259]:
# import nltk

In [260]:
# from nltk.stem.porter import PorterStemmer
# ps=PorterStemmer()

In [261]:
ps.stem('dancing')

'danc'

In [262]:
from sklearn.metrics.pairwise import cosine_similarity

In [263]:
similarity=cosine_similarity(vectors)
similarity

array([[1.        , 0.08458258, 0.08718573, ..., 0.04559608, 0.        ,
        0.        ],
       [0.08458258, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.08718573, 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04559608, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]])

In [264]:
similarity[0]

array([1.        , 0.08458258, 0.08718573, ..., 0.04559608, 0.        ,
       0.        ])

In [265]:
cosine_similarity(vectors).shape

(4800, 4800)

In [266]:
new_df[new_df['title_x']=='Batman Begins'].index[0]

np.int64(119)

In [267]:
def recommend(movie):
  movie_index=new_df[new_df['title_x']==movie].index[0]
  distances=similarity[movie_index]

In [268]:
sorted(similarity[0])[-5:-1]

[np.float64(0.25903973506580724),
 np.float64(0.26401000024165),
 np.float64(0.2726248784031353),
 np.float64(0.29061909685954823)]

In [269]:
enumerate(similarity[0])

In [270]:
similarity[0]

array([1.        , 0.08458258, 0.08718573, ..., 0.04559608, 0.        ,
       0.        ])

In [271]:
list(enumerate(similarity[0]))

[(0, np.float64(0.9999999999999998)),
 (1, np.float64(0.08458258116519013)),
 (2, np.float64(0.08718572905786445)),
 (3, np.float64(0.074458079104994)),
 (4, np.float64(0.19184045508446734)),
 (5, np.float64(0.1098436937909367)),
 (6, np.float64(0.04078236951430929)),
 (7, np.float64(0.1487044791289829)),
 (8, np.float64(0.06003002251876642)),
 (9, np.float64(0.09802861627917438)),
 (10, np.float64(0.10397504898200727)),
 (11, np.float64(0.09592022754223367)),
 (12, np.float64(0.09158437663089952)),
 (13, np.float64(0.04559607525875532)),
 (14, np.float64(0.12996881122750908)),
 (15, np.float64(0.06367145399670132)),
 (16, np.float64(0.08000711205939975)),
 (17, np.float64(0.14273829330008253)),
 (18, np.float64(0.09620723036050562)),
 (19, np.float64(0.08419653359482289)),
 (20, np.float64(0.05881716976750462)),
 (21, np.float64(0.11277677488692017)),
 (22, np.float64(0.06711560552140244)),
 (23, np.float64(0.0885807893036239)),
 (24, np.float64(0.05405405405405406)),
 (25, np.float64(0.05170108966939356)),
 (26, np.float64(0.1559625734730109)),
 (27, np.float64(0.19597660033920403)),
 (28, np.float64(0.11810771907149853)),
 (29, np.float64(0.06590621627456203)),
 (30, np.float64(0.06774581282657174)),
 (31, np.float64(0.16120647005479025)),
 (32, np.float64(0.0863465783552691)),
 (33, np.float64(0.09863939238321438)),
 (34, np.float64(0.0)),
 (35, np.float64(0.10067340828210367)),
 (36, np.float64(0.17348855898381338)),
 (37, np.float64(0.08000711205939975)),
 (38, np.float64(0.08219949365267865)),
 (39, np.float64(0.08336550215650926)),
 (40, np.float64(0.07798128673650545)),
 (41, np.float64(0.1678603981989089)),
 (42, np.float64(0.0)),
 (43, np.float64(0.09208185110322616)),
 (44, np.float64(0.03427955850955305)),
 (45, np.float64(0.08351476906593233)),
 (46, np.float64(0.14097096860865022)),
 (47, np.float64(0.199363055707225)),
 (48, np.float64(0.08561170049453902)),
 (49, np.float64(0.06003002251876642)),
 (50, np.float64(0.1144727614064285)),
 (51, np.float64(0.08094446585163528)),
 (52, np.float64(0.1487044791289829)),
 (53, np.float64(0.04355035563093422)),
 (54, np.float64(0.03163859985841663)),
 (55, np.float64(0.07306621658015879)),
 (56, np.float64(0.14019992744655632)),
 (57, np.float64(0.024507154069793594)),
 (58, np.float64(0.06839411288813299)),
 (59, np.float64(0.07352146220938077)),
 (60, np.float64(0.0186145197762485)),
 (61, np.float64(0.23490461932490855)),
 (62, np.float64(0.08489527199560176)),
 (63, np.float64(0.08284930213349333)),
 (64, np.float64(0.03001501125938321)),
 (65, np.float64(0.01979131233319198)),
 (66, np.float64(0.02279803762937766)),
 (67, np.float64(0.16439898730535726)),
 (68, np.float64(0.1221125021745327)),
 (69, np.float64(0.026846242208560973)),
 (70, np.float64(0.07702442489446452)),
 (71, np.float64(0.07435223956449145)),
 (72, np.float64(0.1389425035941821)),
 (73, np.float64(0.03355780276070122)),
 (74, np.float64(0.20518233866439894)),
 (75, np.float64(0.10529962529853128)),
 (76, np.float64(0.07271792483455794)),
 (77, np.float64(0.014588051152682587)),
 (78, np.float64(0.05134961659630968)),
 (79, np.float64(0.06314740019611717)),
 (80, np.float64(0.05114214254947678)),
 (81, np.float64(0.11168711865749101)),
 (82, np.float64(0.07702442489446452)),
 (83, np.float64(0.1823843010350213)),
 (84, np.float64(0.12527215359889848)),
 (85, np.float64(0.11565903932254226)),
 (86, np.float64(0.07194017065667525)),
 (87, np.float64(0.11277677488692017)),
 (88, np.float64(0.09158437663089954)),
 (89, np.float64(0.058352204610730346)),
 (90, np.float64(0.06213697660012)),
 (91, np.float64(0.16916516233038026)),
 (92, np.float64(0.06314740019611717)),
 (93, np.float64(0.07194017065667525)),
 (94, np.float64(0.1898315991504998)),
 (95, np.float64(0.14237369936287486)),
 (96, np.float64(0.07798128673650545)),
 (97, np.float64(0.07045670884515312)),
 (98, np.float64(0.07610194341477616)),
 (99, np.float64(0.02702702702702703)),
 (100, np.float64(0.0685591170191061)),
 (101, np.float64(0.07798128673650545)),
 (102, np.float64(0.12629480039223434)),
 (103, np.float64(0.08094446585163528)),
 (104, np.float64(0.056388387443460086)),
 (105, np.float64(0.10514994558491725)),
 (106, np.float64(0.06314740019611717)),
 (107, np.float64(0.06263607679944924)),
 (108, np.float64(0.14704292441876157)),
 (109, np.float64(0.06575959492214292)),
 (110, np.float64(0.04559607525875532)),
 (111, np.float64(0.1522038868295523)),
 (112, np.float64(0.07798128673650545)),
 (113, np.float64(0.04393747751637468)),
 (114, np.float64(0.04649905549752771)),
 (115, np.float64(0.04433510985214727)),
 (116, np.float64(0.048478616556371965)),
 (117, np.float64(0.06003002251876642)),
 (118, np.float64(0.034094761699651185)),
 (119, np.float64(0.04393747751637468)),
 (120, np.float64(0.0)),
 (121, np.float64(0.11277677488692017)),
 (122, np.float64(0.11810771907149853)),
 (123, np.float64(0.1139901881468883)),
 (124, np.float64(0.06839411288813299)),
 (125, np.float64(0.07948588753990432)),
 (126, np.float64(0.13513513513513514)),
 (127, np.float64(0.14797064923339878)),
 (128, np.float64(0.0)),
 (129, np.float64(0.09394227846020416)),
 (130, np.float64(0.027399831217559546)),
 (131, np.float64(0.106676149412533)),
 (132, np.float64(0.04559607525875532)),
 (133, np.float64(0.028618190351607124)),
 (134, np.float64(0.13151918984428584)),
 (135, np.float64(0.0)),
 (136, np.float64(0.023728949893812478)),
 (137, np.float64(0.030528125543633176)),
 (138, np.float64(0.12996881122750908)),
 (139, np.float64(0.12234710854292788)),
 (140, np.float64(0.04559607525875532)),
 (141, np.float64(0.0885807893036239)),
 (142, np.float64(0.08585457105482137)),
 (143, np.float64(0.08787495503274936)),
 (144, np.float64(0.050734628943184104)),
 (145, np.float64(0.019510570275964215)),
 (146, np.float64(0.01643989873053573)),
 (147, np.float64(0.056388387443460086)),
 (148, np.float64(0.09863939238321438)),
 (149, np.float64(0.15719549837837185)),
 (150, np.float64(0.16646698038757363)),
 (151, np.float64(0.2056773510573183)),
 (152, np.float64(0.08458258116519013)),
 (153, np.float64(0.07974522228289)),
 (154, np.float64(0.06213697660012)),
 (155, np.float64(0.020712325533373332)),
 (156, np.float64(0.06070834938872646)),
 (157, np.float64(0.10067340828210367)),
 (158, np.float64(0.13549162565314346)),
 (159, np.float64(0.0644825880219161)),
 (160, np.float64(0.11869522585912262)),
 (161, np.float64(0.03224129401095805)),
 (162, np.float64(0.03355780276070122)),
 (163, np.float64(0.05134961659630968)),
 (164, np.float64(0.08108108108108109)),
 (165, np.float64(0.04649905549752771)),
 (166, np.float64(0.12683657235796025)),
 (167, np.float64(0.09158437663089954)),
 (168, np.float64(0.17757120130114434)),
 (169, np.float64(0.08948747402853657)),
 (170, np.float64(0.10793322294408637)),
 (171, np.float64(0.02302046277580654)),
 (172, np.float64(0.21524880100025257)),
 (173, np.float64(0.02348556961505104)),
 (174, np.float64(0.07897471897389846)),
 (175, np.float64(0.07194017065667525)),
 (176, np.float64(0.029526929767874632)),
 (177, np.float64(0.0)),
 (178, np.float64(0.024784079854830485)),
 (179, np.float64(0.07352146220938077)),
 (180, np.float64(0.022371868507134143)),
 (181, np.float64(0.04559607525875532)),
 (182, np.float64(0.1186447494690624)),
 (183, np.float64(0.0713262951621492)),
 (184, np.float64(0.17757120130114434)),
 (185, np.float64(0.05134961659630968)),
 (186, np.float64(0.059808916712167495)),
 (187, np.float64(0.1559625734730109)),
 (188, np.float64(0.022371868507134143)),
 (189, np.float64(0.1162476387438193)),
 (190, np.float64(0.08561170049453902)),
 (191, np.float64(0.04956815970966097)),
 (192, np.float64(0.047960113771116836)),
 (193, np.float64(0.07983920607777244)),
 (194, np.float64(0.0)),
 (195, np.float64(0.06003002251876642)),
 (196, np.float64(0.05264981264926564)),
 (197, np.float64(0.037470006725398436)),
 (198, np.float64(0.058123819371909635)),
 (199, np.float64(0.08787495503274936)),
 (200, np.float64(0.11028219331407116)),
 (201, np.float64(0.0)),
 (202, np.float64(0.03163859985841663)),
 (203, np.float64(0.08458258116519013)),
 (204, np.float64(0.050141221056390024)),
 (205, np.float64(0.07543142864047142)),
 (206, np.float64(0.11241002017619531)),
 (207, np.float64(0.07798128673650545)),
 (208, np.float64(0.12427395320024)),
 (209, np.float64(0.0685591170191061)),
 (210, np.float64(0.07610194341477616)),
 (211, np.float64(0.024784079854830485)),
 (212, np.float64(0.06711560552140243)),
 (213, np.float64(0.059808916712167495)),
 (214, np.float64(0.0)),
 (215, np.float64(0.06711560552140243)),
 (216, np.float64(0.06575959492214292)),
 (217, np.float64(0.0863465783552691)),
 (218, np.float64(0.03874921291460643)),
 (219, np.float64(0.09320546490018)),
 (220, np.float64(0.18009006755629928)),
 (221, np.float64(0.047960113771116836)),
 (222, np.float64(0.08094446585163528)),
 (223, np.float64(0.10529962529853128)),
 (224, np.float64(0.061649620239508984)),
 (225, np.float64(0.047457899787624956)),
 (226, np.float64(0.030528125543633176)),
 (227, np.float64(0.08336550215650926)),
 (228, np.float64(0.11185934253567072)),
 (229, np.float64(0.10892898631973956)),
 (230, np.float64(0.0930725988812425)),
 (231, np.float64(0.0)),
 (232, np.float64(0.11277677488692017)),
 (233, np.float64(0.10514994558491725)),
 (234, np.float64(0.08710071126186844)),
 (235, np.float64(0.07702442489446452)),
 (236, np.float64(0.11624763874381927)),
 (237, np.float64(0.06711560552140244)),
 (238, np.float64(0.11241002017619531)),
 (239, np.float64(0.09248165577087425)),
 (240, np.float64(0.047457899787624956)),
 (241, np.float64(0.08000711205939975)),
 (242, np.float64(0.08219949365267865)),
 (243, np.float64(0.09394227846020416)),
 (244, np.float64(0.09320546490018)),
 (245, np.float64(0.08219949365267865)),
 (246, np.float64(0.07696578428840449)),
 (247, np.float64(0.0)),
 (248, np.float64(0.04516387521771449)),
 (249, np.float64(0.14019992744655632)),
 (250, np.float64(0.0)),
 (251, np.float64(0.04244763599780088)),
 (252, np.float64(0.02054987341316966)),
 (253, np.float64(0.06367145399670132)),
 (254, np.float64(0.07045670884515312)),
 (255, np.float64(0.0)),
 (256, np.float64(0.11314714296070713)),
 (257, np.float64(0.05405405405405406)),
 (258, np.float64(0.01793740008335438)),
 (259, np.float64(0.06213697660012)),
 (260, np.float64(0.20668850837512243)),
 (261, np.float64(0.024507154069793594)),
 (262, np.float64(0.10793322294408637)),
 (263, np.float64(0.09863939238321438)),
 (264, np.float64(0.0)),
 (265, np.float64(0.027788500718836418)),
 (266, np.float64(0.10028244211278005)),
 (267, np.float64(0.06575959492214292)),
 (268, np.float64(0.0533380747062665)),
 (269, np.float64(0.03001501125938321)),
 (270, np.float64(0.08948747402853657)),
 (271, np.float64(0.07194017065667525)),
 (272, np.float64(0.028194193721730043)),
 (273, np.float64(0.021402925123634755)),
 (274, np.float64(0.09097816785925636)),
 (275, np.float64(0.1453095484297741)),
 (276, np.float64(0.06327719971683327)),
 (277, np.float64(0.05381220025006314)),
 (278, np.float64(0.1186447494690624)),
 (279, np.float64(0.09394227846020416)),
 (280, np.float64(0.0)),
 (281, np.float64(0.06590621627456203)),
 (282, np.float64(0.04516387521771449)),
 (283, np.float64(0.027788500718836418)),
 (284, np.float64(0.0186145197762485)),
 (285, np.float64(0.01979131233319198)),
 (286, np.float64(0.07916524933276792)),
 (287, np.float64(0.02632490632463282)),
 (288, np.float64(0.027788500718836418)),
 (289, np.float64(0.04649905549752771)),
 (290, np.float64(0.06327719971683327)),
 (291, np.float64(0.050141221056390024)),
 (292, np.float64(0.09004503377814962)),
 (293, np.float64(0.03001501125938321)),
 (294, np.float64(0.1453095484297741)),
 (295, np.float64(0.106676149412533)),
 (296, np.float64(0.03929887459459296)),
 (297, np.float64(0.04474373701426829)),
 (298, np.float64(0.0)),
 (299, np.float64(0.06025359879550432)),
 (300, np.float64(0.17348855898381338)),
 (301, np.float64(0.09491579957524988)),
 (302, np.float64(0.07045670884515312)),
 (303, np.float64(0.028194193721730043)),
 (304, np.float64(0.06667259338283313)),
 (305, np.float64(0.1926263261127128)),
 (306, np.float64(0.08219949365267865)),
 (307, np.float64(0.11022596991336672)),
 (308, np.float64(0.0685591170191061)),
 (309, np.float64(0.06327719971683327)),
 (310, np.float64(0.03106848830006)),
 (311, np.float64(0.1522038868295523)),
 (312, np.float64(0.10146925788636821)),
 (313, np.float64(0.055577001437672836)),
 (314, np.float64(0.0)),
 (315, np.float64(0.08458258116519013)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.10067340828210367)),
 (320, np.float64(0.03106848830006)),
 (321, np.float64(0.0)),
 (322, np.float64(0.213352298825066)),
 (323, np.float64(0.03001501125938321)),
 (324, np.float64(0.024507154069793594)),
 (325, np.float64(0.10067340828210367)),
 (326, np.float64(0.05723638070321425)),
 (327, np.float64(0.027788500718836418)),
 (328, np.float64(0.027788500718836418)),
 (329, np.float64(0.08000711205939975)),
 (330, np.float64(0.10146925788636821)),
 (331, np.float64(0.09119215051751065)),
 (332, np.float64(0.10810810810810811)),
 (333, np.float64(0.024784079854830485)),
 (334, np.float64(0.09802861627917438)),
 (335, np.float64(0.04697113923010208)),
 (336, np.float64(0.07009996372327816)),
 (337, np.float64(0.04604092555161308)),
 (338, np.float64(0.0)),
 (339, np.float64(0.04956815970966097)),
 (340, np.float64(0.050141221056390024)),
 (341, np.float64(0.08336550215650926)),
 (342, np.float64(0.1633934794796094)),
 (343, np.float64(0.019510570275964215)),
 (344, np.float64(0.03001501125938321)),
 (345, np.float64(0.023249527748763855)),
 (346, np.float64(0.0)),
 (347, np.float64(0.0)),
 (348, np.float64(0.06213697660012)),
 (349, np.float64(0.07702442489446452)),
 (350, np.float64(0.04956815970966097)),
 (351, np.float64(0.0)),
 (352, np.float64(0.027788500718836418)),
 (353, np.float64(0.041757384532966166)),
 (354, np.float64(0.02196873875818734)),
 (355, np.float64(0.036992662308349696)),
 (356, np.float64(0.09158437663089952)),
 (357, np.float64(0.0)),
 (358, np.float64(0.06105625108726635)),
 (359, np.float64(0.03163859985841663)),
 (360, np.float64(0.02122381799890044)),
 (361, np.float64(0.07610194341477616)),
 (362, np.float64(0.09672388203287416)),
 (363, np.float64(0.10042266465917388)),
 (364, np.float64(0.023728949893812478)),
 (365, np.float64(0.07610194341477616)),
 (366, np.float64(0.05723638070321425)),
 (367, np.float64(0.0)),
 (368, np.float64(0.13151918984428584)),
 (369, np.float64(0.08108108108108109)),
 (370, np.float64(0.05134961659630968)),
 (371, np.float64(0.09695723311274393)),
 (372, np.float64(0.047960113771116836)),
 (373, np.float64(0.1752499093081954)),
 (374, np.float64(0.038482892144202245)),
 (375, np.float64(0.06213697660011999)),
 (376, np.float64(0.047457899787624956)),
 (377, np.float64(0.0)),
 (378, np.float64(0.0)),
 (379, np.float64(0.05141933776432957)),
 (380, np.float64(0.05264981264926564)),
 (381, np.float64(0.08489527199560176)),
 (382, np.float64(0.0)),
 (383, np.float64(0.04393747751637468)),
 (384, np.float64(0.029061909685954818)),
 (385, np.float64(0.0)),
 (386, np.float64(0.022167554926073633)),
 (387, np.float64(0.023980056885558418)),
 (388, np.float64(0.0)),
 (389, np.float64(0.0885807893036239)),
 (390, np.float64(0.02666903735313325)),
 (391, np.float64(0.05733298225836872)),
 (392, np.float64(0.030528125543633176)),
 (393, np.float64(0.0)),
 (394, np.float64(0.025070610528195012)),
 (395, np.float64(0.05264981264926564)),
 (396, np.float64(0.04433510985214727)),
 (397, np.float64(0.05264981264926564)),
 (398, np.float64(0.0)),
 (399, np.float64(0.023980056885558418)),
 (400, np.float64(0.09158437663089952)),
 (401, np.float64(0.03106848830006)),
 (402, np.float64(0.07897471897389846)),
 (403, np.float64(0.08419653359482289)),
 (404, np.float64(0.06213697660012)),
 (405, np.float64(0.056388387443460086)),
 (406, np.float64(0.021049133398705722)),
 (407, np.float64(0.021586644588817275)),
 (408, np.float64(0.03287979746107146)),
 (409, np.float64(0.0)),
 (410, np.float64(0.09913631941932194)),
 (411, np.float64(0.0533380747062665)),
 (412, np.float64(0.09695723311274393)),
 (413, np.float64(0.14309095175803563)),
 (414, np.float64(0.03001501125938321)),
 (415, np.float64(0.05413539955388112)),
 (416, np.float64(0.05134961659630968)),
 (417, np.float64(0.03287979746107146)),
 (418, np.float64(0.03587480016670876)),
 (419, np.float64(0.06974858324629157)),
 (420, np.float64(0.1139901881468883)),
 (421, np.float64(0.02348556961505104)),
 (422, np.float64(0.11810771907149853)),
 (423, np.float64(0.041757384532966166)),
 (424, np.float64(0.037470006725398436)),
 (425, np.float64(0.06475993376645182)),
 (426, np.float64(0.05446449315986979)),
 (427, np.float64(0.02666903735313325)),
 (428, np.float64(0.056573571480353566)),
 (429, np.float64(0.0)),
 (430, np.float64(0.05134961659630968)),
 (431, np.float64(0.024507154069793594)),
 (432, np.float64(0.11510231387903269)),
 (433, np.float64(0.03163859985841663)),
 (434, np.float64(0.0)),
 (435, np.float64(0.03587480016670876)),
 (436, np.float64(0.0)),
 (437, np.float64(0.025993762245501817)),
 (438, np.float64(0.12392039927415242)),
 (439, np.float64(0.02666903735313325)),
 (440, np.float64(0.025070610528195012)),
 (441, np.float64(0.058123819371909635)),
 (442, np.float64(0.04604092555161308)),
 (443, np.float64(0.06475993376645182)),
 (444, np.float64(0.0)),
 (445, np.float64(0.10028244211278005)),
 (446, np.float64(0.02348556961505104)),
 (447, np.float64(0.06532553344640132)),
 (448, np.float64(0.021586644588817275)),
 (449, np.float64(0.11115400287534567)),
 (450, np.float64(0.021586644588817275)),
 (451, np.float64(0.025367314471592052)),
 (452, np.float64(0.03106848830006)),
 (453, np.float64(0.024784079854830485)),
 (454, np.float64(0.11742784807525519)),
 (455, np.float64(0.061649620239508984)),
 (456, np.float64(0.04393747751637468)),
 (457, np.float64(0.08718572905786445)),
 (458, np.float64(0.04393747751637468)),
 (459, np.float64(0.03504998186163908)),
 (460, np.float64(0.024507154069793594)),
 (461, np.float64(0.14309095175803563)),
 (462, np.float64(0.03271662128033808)),
 (463, np.float64(0.03287979746107146)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.14704292441876154)),
 (467, np.float64(0.10701462561817378)),
 (468, np.float64(0.028194193721730043)),
 (469, np.float64(0.06025359879550432)),
 (470, np.float64(0.04604092555161308)),
 (471, np.float64(0.06475993376645182)),
 (472, np.float64(0.10810810810810811)),
 (473, np.float64(0.09394227846020416)),
 (474, np.float64(0.0)),
 (475, np.float64(0.04433510985214727)),
 (476, np.float64(0.1371182340382122)),
 (477, np.float64(0.0)),
 (478, np.float64(0.05479966243511909)),
 (479, np.float64(0.0891578689526865)),
 (480, np.float64(0.09913631941932194)),
 (481, np.float64(0.0)),
 (482, np.float64(0.022167554926073633)),
 (483, np.float64(0.12655439943366653)),
 (484, np.float64(0.029526929767874632)),
 (485, np.float64(0.0533380747062665)),
 (486, np.float64(0.08099356774626426)),
 (487, np.float64(0.1289651760438322)),
 (488, np.float64(0.06746792083200746)),
 (489, np.float64(0.0)),
 (490, np.float64(0.14349920066683505)),
 (491, np.float64(0.10042266465917388)),
 (492, np.float64(0.07702442489446452)),
 (493, np.float64(0.03106848830006)),
 (494, np.float64(0.0)),
 (495, np.float64(0.19344776406574832)),
 (496, np.float64(0.0)),
 (497, np.float64(0.0)),
 (498, np.float64(0.0685591170191061)),
 (499, np.float64(0.0)),
 (500, np.float64(0.02632490632463282)),
 (501, np.float64(0.08284930213349333)),
 (502, np.float64(0.13549162565314346)),
 (503, np.float64(0.07610194341477615)),
 (504, np.float64(0.0)),
 (505, np.float64(0.1371182340382122)),
 (506, np.float64(0.03504998186163908)),
 (507, np.float64(0.25903973506580724)),
 (508, np.float64(0.10269923319261937)),
 (509, np.float64(0.022371868507134143)),

In [272]:
sorted(list(enumerate(similarity[0])))

[(0, np.float64(0.9999999999999998)),
 (1, np.float64(0.08458258116519013)),
 (2, np.float64(0.08718572905786445)),
 (3, np.float64(0.074458079104994)),
 (4, np.float64(0.19184045508446734)),
 (5, np.float64(0.1098436937909367)),
 (6, np.float64(0.04078236951430929)),
 (7, np.float64(0.1487044791289829)),
 (8, np.float64(0.06003002251876642)),
 (9, np.float64(0.09802861627917438)),
 (10, np.float64(0.10397504898200727)),
 (11, np.float64(0.09592022754223367)),
 (12, np.float64(0.09158437663089952)),
 (13, np.float64(0.04559607525875532)),
 (14, np.float64(0.12996881122750908)),
 (15, np.float64(0.06367145399670132)),
 (16, np.float64(0.08000711205939975)),
 (17, np.float64(0.14273829330008253)),
 (18, np.float64(0.09620723036050562)),
 (19, np.float64(0.08419653359482289)),
 (20, np.float64(0.05881716976750462)),
 (21, np.float64(0.11277677488692017)),
 (22, np.float64(0.06711560552140244)),
 (23, np.float64(0.0885807893036239)),
 (24, np.float64(0.05405405405405406)),
 (25, np.float64(0.05170108966939356)),
 (26, np.float64(0.1559625734730109)),
 (27, np.float64(0.19597660033920403)),
 (28, np.float64(0.11810771907149853)),
 (29, np.float64(0.06590621627456203)),
 (30, np.float64(0.06774581282657174)),
 (31, np.float64(0.16120647005479025)),
 (32, np.float64(0.0863465783552691)),
 (33, np.float64(0.09863939238321438)),
 (34, np.float64(0.0)),
 (35, np.float64(0.10067340828210367)),
 (36, np.float64(0.17348855898381338)),
 (37, np.float64(0.08000711205939975)),
 (38, np.float64(0.08219949365267865)),
 (39, np.float64(0.08336550215650926)),
 (40, np.float64(0.07798128673650545)),
 (41, np.float64(0.1678603981989089)),
 (42, np.float64(0.0)),
 (43, np.float64(0.09208185110322616)),
 (44, np.float64(0.03427955850955305)),
 (45, np.float64(0.08351476906593233)),
 (46, np.float64(0.14097096860865022)),
 (47, np.float64(0.199363055707225)),
 (48, np.float64(0.08561170049453902)),
 (49, np.float64(0.06003002251876642)),
 (50, np.float64(0.1144727614064285)),
 (51, np.float64(0.08094446585163528)),
 (52, np.float64(0.1487044791289829)),
 (53, np.float64(0.04355035563093422)),
 (54, np.float64(0.03163859985841663)),
 (55, np.float64(0.07306621658015879)),
 (56, np.float64(0.14019992744655632)),
 (57, np.float64(0.024507154069793594)),
 (58, np.float64(0.06839411288813299)),
 (59, np.float64(0.07352146220938077)),
 (60, np.float64(0.0186145197762485)),
 (61, np.float64(0.23490461932490855)),
 (62, np.float64(0.08489527199560176)),
 (63, np.float64(0.08284930213349333)),
 (64, np.float64(0.03001501125938321)),
 (65, np.float64(0.01979131233319198)),
 (66, np.float64(0.02279803762937766)),
 (67, np.float64(0.16439898730535726)),
 (68, np.float64(0.1221125021745327)),
 (69, np.float64(0.026846242208560973)),
 (70, np.float64(0.07702442489446452)),
 (71, np.float64(0.07435223956449145)),
 (72, np.float64(0.1389425035941821)),
 (73, np.float64(0.03355780276070122)),
 (74, np.float64(0.20518233866439894)),
 (75, np.float64(0.10529962529853128)),
 (76, np.float64(0.07271792483455794)),
 (77, np.float64(0.014588051152682587)),
 (78, np.float64(0.05134961659630968)),
 (79, np.float64(0.06314740019611717)),
 (80, np.float64(0.05114214254947678)),
 (81, np.float64(0.11168711865749101)),
 (82, np.float64(0.07702442489446452)),
 (83, np.float64(0.1823843010350213)),
 (84, np.float64(0.12527215359889848)),
 (85, np.float64(0.11565903932254226)),
 (86, np.float64(0.07194017065667525)),
 (87, np.float64(0.11277677488692017)),
 (88, np.float64(0.09158437663089954)),
 (89, np.float64(0.058352204610730346)),
 (90, np.float64(0.06213697660012)),
 (91, np.float64(0.16916516233038026)),
 (92, np.float64(0.06314740019611717)),
 (93, np.float64(0.07194017065667525)),
 (94, np.float64(0.1898315991504998)),
 (95, np.float64(0.14237369936287486)),
 (96, np.float64(0.07798128673650545)),
 (97, np.float64(0.07045670884515312)),
 (98, np.float64(0.07610194341477616)),
 (99, np.float64(0.02702702702702703)),
 (100, np.float64(0.0685591170191061)),
 (101, np.float64(0.07798128673650545)),
 (102, np.float64(0.12629480039223434)),
 (103, np.float64(0.08094446585163528)),
 (104, np.float64(0.056388387443460086)),
 (105, np.float64(0.10514994558491725)),
 (106, np.float64(0.06314740019611717)),
 (107, np.float64(0.06263607679944924)),
 (108, np.float64(0.14704292441876157)),
 (109, np.float64(0.06575959492214292)),
 (110, np.float64(0.04559607525875532)),
 (111, np.float64(0.1522038868295523)),
 (112, np.float64(0.07798128673650545)),
 (113, np.float64(0.04393747751637468)),
 (114, np.float64(0.04649905549752771)),
 (115, np.float64(0.04433510985214727)),
 (116, np.float64(0.048478616556371965)),
 (117, np.float64(0.06003002251876642)),
 (118, np.float64(0.034094761699651185)),
 (119, np.float64(0.04393747751637468)),
 (120, np.float64(0.0)),
 (121, np.float64(0.11277677488692017)),
 (122, np.float64(0.11810771907149853)),
 (123, np.float64(0.1139901881468883)),
 (124, np.float64(0.06839411288813299)),
 (125, np.float64(0.07948588753990432)),
 (126, np.float64(0.13513513513513514)),
 (127, np.float64(0.14797064923339878)),
 (128, np.float64(0.0)),
 (129, np.float64(0.09394227846020416)),
 (130, np.float64(0.027399831217559546)),
 (131, np.float64(0.106676149412533)),
 (132, np.float64(0.04559607525875532)),
 (133, np.float64(0.028618190351607124)),
 (134, np.float64(0.13151918984428584)),
 (135, np.float64(0.0)),
 (136, np.float64(0.023728949893812478)),
 (137, np.float64(0.030528125543633176)),
 (138, np.float64(0.12996881122750908)),
 (139, np.float64(0.12234710854292788)),
 (140, np.float64(0.04559607525875532)),
 (141, np.float64(0.0885807893036239)),
 (142, np.float64(0.08585457105482137)),
 (143, np.float64(0.08787495503274936)),
 (144, np.float64(0.050734628943184104)),
 (145, np.float64(0.019510570275964215)),
 (146, np.float64(0.01643989873053573)),
 (147, np.float64(0.056388387443460086)),
 (148, np.float64(0.09863939238321438)),
 (149, np.float64(0.15719549837837185)),
 (150, np.float64(0.16646698038757363)),
 (151, np.float64(0.2056773510573183)),
 (152, np.float64(0.08458258116519013)),
 (153, np.float64(0.07974522228289)),
 (154, np.float64(0.06213697660012)),
 (155, np.float64(0.020712325533373332)),
 (156, np.float64(0.06070834938872646)),
 (157, np.float64(0.10067340828210367)),
 (158, np.float64(0.13549162565314346)),
 (159, np.float64(0.0644825880219161)),
 (160, np.float64(0.11869522585912262)),
 (161, np.float64(0.03224129401095805)),
 (162, np.float64(0.03355780276070122)),
 (163, np.float64(0.05134961659630968)),
 (164, np.float64(0.08108108108108109)),
 (165, np.float64(0.04649905549752771)),
 (166, np.float64(0.12683657235796025)),
 (167, np.float64(0.09158437663089954)),
 (168, np.float64(0.17757120130114434)),
 (169, np.float64(0.08948747402853657)),
 (170, np.float64(0.10793322294408637)),
 (171, np.float64(0.02302046277580654)),
 (172, np.float64(0.21524880100025257)),
 (173, np.float64(0.02348556961505104)),
 (174, np.float64(0.07897471897389846)),
 (175, np.float64(0.07194017065667525)),
 (176, np.float64(0.029526929767874632)),
 (177, np.float64(0.0)),
 (178, np.float64(0.024784079854830485)),
 (179, np.float64(0.07352146220938077)),
 (180, np.float64(0.022371868507134143)),
 (181, np.float64(0.04559607525875532)),
 (182, np.float64(0.1186447494690624)),
 (183, np.float64(0.0713262951621492)),
 (184, np.float64(0.17757120130114434)),
 (185, np.float64(0.05134961659630968)),
 (186, np.float64(0.059808916712167495)),
 (187, np.float64(0.1559625734730109)),
 (188, np.float64(0.022371868507134143)),
 (189, np.float64(0.1162476387438193)),
 (190, np.float64(0.08561170049453902)),
 (191, np.float64(0.04956815970966097)),
 (192, np.float64(0.047960113771116836)),
 (193, np.float64(0.07983920607777244)),
 (194, np.float64(0.0)),
 (195, np.float64(0.06003002251876642)),
 (196, np.float64(0.05264981264926564)),
 (197, np.float64(0.037470006725398436)),
 (198, np.float64(0.058123819371909635)),
 (199, np.float64(0.08787495503274936)),
 (200, np.float64(0.11028219331407116)),
 (201, np.float64(0.0)),
 (202, np.float64(0.03163859985841663)),
 (203, np.float64(0.08458258116519013)),
 (204, np.float64(0.050141221056390024)),
 (205, np.float64(0.07543142864047142)),
 (206, np.float64(0.11241002017619531)),
 (207, np.float64(0.07798128673650545)),
 (208, np.float64(0.12427395320024)),
 (209, np.float64(0.0685591170191061)),
 (210, np.float64(0.07610194341477616)),
 (211, np.float64(0.024784079854830485)),
 (212, np.float64(0.06711560552140243)),
 (213, np.float64(0.059808916712167495)),
 (214, np.float64(0.0)),
 (215, np.float64(0.06711560552140243)),
 (216, np.float64(0.06575959492214292)),
 (217, np.float64(0.0863465783552691)),
 (218, np.float64(0.03874921291460643)),
 (219, np.float64(0.09320546490018)),
 (220, np.float64(0.18009006755629928)),
 (221, np.float64(0.047960113771116836)),
 (222, np.float64(0.08094446585163528)),
 (223, np.float64(0.10529962529853128)),
 (224, np.float64(0.061649620239508984)),
 (225, np.float64(0.047457899787624956)),
 (226, np.float64(0.030528125543633176)),
 (227, np.float64(0.08336550215650926)),
 (228, np.float64(0.11185934253567072)),
 (229, np.float64(0.10892898631973956)),
 (230, np.float64(0.0930725988812425)),
 (231, np.float64(0.0)),
 (232, np.float64(0.11277677488692017)),
 (233, np.float64(0.10514994558491725)),
 (234, np.float64(0.08710071126186844)),
 (235, np.float64(0.07702442489446452)),
 (236, np.float64(0.11624763874381927)),
 (237, np.float64(0.06711560552140244)),
 (238, np.float64(0.11241002017619531)),
 (239, np.float64(0.09248165577087425)),
 (240, np.float64(0.047457899787624956)),
 (241, np.float64(0.08000711205939975)),
 (242, np.float64(0.08219949365267865)),
 (243, np.float64(0.09394227846020416)),
 (244, np.float64(0.09320546490018)),
 (245, np.float64(0.08219949365267865)),
 (246, np.float64(0.07696578428840449)),
 (247, np.float64(0.0)),
 (248, np.float64(0.04516387521771449)),
 (249, np.float64(0.14019992744655632)),
 (250, np.float64(0.0)),
 (251, np.float64(0.04244763599780088)),
 (252, np.float64(0.02054987341316966)),
 (253, np.float64(0.06367145399670132)),
 (254, np.float64(0.07045670884515312)),
 (255, np.float64(0.0)),
 (256, np.float64(0.11314714296070713)),
 (257, np.float64(0.05405405405405406)),
 (258, np.float64(0.01793740008335438)),
 (259, np.float64(0.06213697660012)),
 (260, np.float64(0.20668850837512243)),
 (261, np.float64(0.024507154069793594)),
 (262, np.float64(0.10793322294408637)),
 (263, np.float64(0.09863939238321438)),
 (264, np.float64(0.0)),
 (265, np.float64(0.027788500718836418)),
 (266, np.float64(0.10028244211278005)),
 (267, np.float64(0.06575959492214292)),
 (268, np.float64(0.0533380747062665)),
 (269, np.float64(0.03001501125938321)),
 (270, np.float64(0.08948747402853657)),
 (271, np.float64(0.07194017065667525)),
 (272, np.float64(0.028194193721730043)),
 (273, np.float64(0.021402925123634755)),
 (274, np.float64(0.09097816785925636)),
 (275, np.float64(0.1453095484297741)),
 (276, np.float64(0.06327719971683327)),
 (277, np.float64(0.05381220025006314)),
 (278, np.float64(0.1186447494690624)),
 (279, np.float64(0.09394227846020416)),
 (280, np.float64(0.0)),
 (281, np.float64(0.06590621627456203)),
 (282, np.float64(0.04516387521771449)),
 (283, np.float64(0.027788500718836418)),
 (284, np.float64(0.0186145197762485)),
 (285, np.float64(0.01979131233319198)),
 (286, np.float64(0.07916524933276792)),
 (287, np.float64(0.02632490632463282)),
 (288, np.float64(0.027788500718836418)),
 (289, np.float64(0.04649905549752771)),
 (290, np.float64(0.06327719971683327)),
 (291, np.float64(0.050141221056390024)),
 (292, np.float64(0.09004503377814962)),
 (293, np.float64(0.03001501125938321)),
 (294, np.float64(0.1453095484297741)),
 (295, np.float64(0.106676149412533)),
 (296, np.float64(0.03929887459459296)),
 (297, np.float64(0.04474373701426829)),
 (298, np.float64(0.0)),
 (299, np.float64(0.06025359879550432)),
 (300, np.float64(0.17348855898381338)),
 (301, np.float64(0.09491579957524988)),
 (302, np.float64(0.07045670884515312)),
 (303, np.float64(0.028194193721730043)),
 (304, np.float64(0.06667259338283313)),
 (305, np.float64(0.1926263261127128)),
 (306, np.float64(0.08219949365267865)),
 (307, np.float64(0.11022596991336672)),
 (308, np.float64(0.0685591170191061)),
 (309, np.float64(0.06327719971683327)),
 (310, np.float64(0.03106848830006)),
 (311, np.float64(0.1522038868295523)),
 (312, np.float64(0.10146925788636821)),
 (313, np.float64(0.055577001437672836)),
 (314, np.float64(0.0)),
 (315, np.float64(0.08458258116519013)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.10067340828210367)),
 (320, np.float64(0.03106848830006)),
 (321, np.float64(0.0)),
 (322, np.float64(0.213352298825066)),
 (323, np.float64(0.03001501125938321)),
 (324, np.float64(0.024507154069793594)),
 (325, np.float64(0.10067340828210367)),
 (326, np.float64(0.05723638070321425)),
 (327, np.float64(0.027788500718836418)),
 (328, np.float64(0.027788500718836418)),
 (329, np.float64(0.08000711205939975)),
 (330, np.float64(0.10146925788636821)),
 (331, np.float64(0.09119215051751065)),
 (332, np.float64(0.10810810810810811)),
 (333, np.float64(0.024784079854830485)),
 (334, np.float64(0.09802861627917438)),
 (335, np.float64(0.04697113923010208)),
 (336, np.float64(0.07009996372327816)),
 (337, np.float64(0.04604092555161308)),
 (338, np.float64(0.0)),
 (339, np.float64(0.04956815970966097)),
 (340, np.float64(0.050141221056390024)),
 (341, np.float64(0.08336550215650926)),
 (342, np.float64(0.1633934794796094)),
 (343, np.float64(0.019510570275964215)),
 (344, np.float64(0.03001501125938321)),
 (345, np.float64(0.023249527748763855)),
 (346, np.float64(0.0)),
 (347, np.float64(0.0)),
 (348, np.float64(0.06213697660012)),
 (349, np.float64(0.07702442489446452)),
 (350, np.float64(0.04956815970966097)),
 (351, np.float64(0.0)),
 (352, np.float64(0.027788500718836418)),
 (353, np.float64(0.041757384532966166)),
 (354, np.float64(0.02196873875818734)),
 (355, np.float64(0.036992662308349696)),
 (356, np.float64(0.09158437663089952)),
 (357, np.float64(0.0)),
 (358, np.float64(0.06105625108726635)),
 (359, np.float64(0.03163859985841663)),
 (360, np.float64(0.02122381799890044)),
 (361, np.float64(0.07610194341477616)),
 (362, np.float64(0.09672388203287416)),
 (363, np.float64(0.10042266465917388)),
 (364, np.float64(0.023728949893812478)),
 (365, np.float64(0.07610194341477616)),
 (366, np.float64(0.05723638070321425)),
 (367, np.float64(0.0)),
 (368, np.float64(0.13151918984428584)),
 (369, np.float64(0.08108108108108109)),
 (370, np.float64(0.05134961659630968)),
 (371, np.float64(0.09695723311274393)),
 (372, np.float64(0.047960113771116836)),
 (373, np.float64(0.1752499093081954)),
 (374, np.float64(0.038482892144202245)),
 (375, np.float64(0.06213697660011999)),
 (376, np.float64(0.047457899787624956)),
 (377, np.float64(0.0)),
 (378, np.float64(0.0)),
 (379, np.float64(0.05141933776432957)),
 (380, np.float64(0.05264981264926564)),
 (381, np.float64(0.08489527199560176)),
 (382, np.float64(0.0)),
 (383, np.float64(0.04393747751637468)),
 (384, np.float64(0.029061909685954818)),
 (385, np.float64(0.0)),
 (386, np.float64(0.022167554926073633)),
 (387, np.float64(0.023980056885558418)),
 (388, np.float64(0.0)),
 (389, np.float64(0.0885807893036239)),
 (390, np.float64(0.02666903735313325)),
 (391, np.float64(0.05733298225836872)),
 (392, np.float64(0.030528125543633176)),
 (393, np.float64(0.0)),
 (394, np.float64(0.025070610528195012)),
 (395, np.float64(0.05264981264926564)),
 (396, np.float64(0.04433510985214727)),
 (397, np.float64(0.05264981264926564)),
 (398, np.float64(0.0)),
 (399, np.float64(0.023980056885558418)),
 (400, np.float64(0.09158437663089952)),
 (401, np.float64(0.03106848830006)),
 (402, np.float64(0.07897471897389846)),
 (403, np.float64(0.08419653359482289)),
 (404, np.float64(0.06213697660012)),
 (405, np.float64(0.056388387443460086)),
 (406, np.float64(0.021049133398705722)),
 (407, np.float64(0.021586644588817275)),
 (408, np.float64(0.03287979746107146)),
 (409, np.float64(0.0)),
 (410, np.float64(0.09913631941932194)),
 (411, np.float64(0.0533380747062665)),
 (412, np.float64(0.09695723311274393)),
 (413, np.float64(0.14309095175803563)),
 (414, np.float64(0.03001501125938321)),
 (415, np.float64(0.05413539955388112)),
 (416, np.float64(0.05134961659630968)),
 (417, np.float64(0.03287979746107146)),
 (418, np.float64(0.03587480016670876)),
 (419, np.float64(0.06974858324629157)),
 (420, np.float64(0.1139901881468883)),
 (421, np.float64(0.02348556961505104)),
 (422, np.float64(0.11810771907149853)),
 (423, np.float64(0.041757384532966166)),
 (424, np.float64(0.037470006725398436)),
 (425, np.float64(0.06475993376645182)),
 (426, np.float64(0.05446449315986979)),
 (427, np.float64(0.02666903735313325)),
 (428, np.float64(0.056573571480353566)),
 (429, np.float64(0.0)),
 (430, np.float64(0.05134961659630968)),
 (431, np.float64(0.024507154069793594)),
 (432, np.float64(0.11510231387903269)),
 (433, np.float64(0.03163859985841663)),
 (434, np.float64(0.0)),
 (435, np.float64(0.03587480016670876)),
 (436, np.float64(0.0)),
 (437, np.float64(0.025993762245501817)),
 (438, np.float64(0.12392039927415242)),
 (439, np.float64(0.02666903735313325)),
 (440, np.float64(0.025070610528195012)),
 (441, np.float64(0.058123819371909635)),
 (442, np.float64(0.04604092555161308)),
 (443, np.float64(0.06475993376645182)),
 (444, np.float64(0.0)),
 (445, np.float64(0.10028244211278005)),
 (446, np.float64(0.02348556961505104)),
 (447, np.float64(0.06532553344640132)),
 (448, np.float64(0.021586644588817275)),
 (449, np.float64(0.11115400287534567)),
 (450, np.float64(0.021586644588817275)),
 (451, np.float64(0.025367314471592052)),
 (452, np.float64(0.03106848830006)),
 (453, np.float64(0.024784079854830485)),
 (454, np.float64(0.11742784807525519)),
 (455, np.float64(0.061649620239508984)),
 (456, np.float64(0.04393747751637468)),
 (457, np.float64(0.08718572905786445)),
 (458, np.float64(0.04393747751637468)),
 (459, np.float64(0.03504998186163908)),
 (460, np.float64(0.024507154069793594)),
 (461, np.float64(0.14309095175803563)),
 (462, np.float64(0.03271662128033808)),
 (463, np.float64(0.03287979746107146)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.14704292441876154)),
 (467, np.float64(0.10701462561817378)),
 (468, np.float64(0.028194193721730043)),
 (469, np.float64(0.06025359879550432)),
 (470, np.float64(0.04604092555161308)),
 (471, np.float64(0.06475993376645182)),
 (472, np.float64(0.10810810810810811)),
 (473, np.float64(0.09394227846020416)),
 (474, np.float64(0.0)),
 (475, np.float64(0.04433510985214727)),
 (476, np.float64(0.1371182340382122)),
 (477, np.float64(0.0)),
 (478, np.float64(0.05479966243511909)),
 (479, np.float64(0.0891578689526865)),
 (480, np.float64(0.09913631941932194)),
 (481, np.float64(0.0)),
 (482, np.float64(0.022167554926073633)),
 (483, np.float64(0.12655439943366653)),
 (484, np.float64(0.029526929767874632)),
 (485, np.float64(0.0533380747062665)),
 (486, np.float64(0.08099356774626426)),
 (487, np.float64(0.1289651760438322)),
 (488, np.float64(0.06746792083200746)),
 (489, np.float64(0.0)),
 (490, np.float64(0.14349920066683505)),
 (491, np.float64(0.10042266465917388)),
 (492, np.float64(0.07702442489446452)),
 (493, np.float64(0.03106848830006)),
 (494, np.float64(0.0)),
 (495, np.float64(0.19344776406574832)),
 (496, np.float64(0.0)),
 (497, np.float64(0.0)),
 (498, np.float64(0.0685591170191061)),
 (499, np.float64(0.0)),
 (500, np.float64(0.02632490632463282)),
 (501, np.float64(0.08284930213349333)),
 (502, np.float64(0.13549162565314346)),
 (503, np.float64(0.07610194341477615)),
 (504, np.float64(0.0)),
 (505, np.float64(0.1371182340382122)),
 (506, np.float64(0.03504998186163908)),
 (507, np.float64(0.25903973506580724)),
 (508, np.float64(0.10269923319261937)),
 (509, np.float64(0.022371868507134143)),

HERE WE WNAT TO SORT THE VALUES ON THE BASIS OF INDEX

In [273]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1213, np.float64(0.29061909685954823)),
 (2403, np.float64(0.2726248784031353)),
 (3723, np.float64(0.26401000024165)),
 (507, np.float64(0.25903973506580724)),
 (539, np.float64(0.2537477434955704))]

In [274]:
def recommend(movie):
  movie_index=new_df[new_df['title_x']==movie].index[0]
  distances=similarity[movie_index]
  movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
  for i in movies_list:
    print(new_df.iloc[i[0]].title_x)

In [275]:
recommend('Spectre')

Quantum of Solace
Skyfall
Never Say Never Again
From Russia with Love
Octopussy

In [276]:
recommend('Avatar')

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [277]:
import pickle

In [278]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [284]:
new_df['title_x'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [285]:
movies_dict2 = movies.to_dict()

In [286]:
pickle.dump(new_df.to_dict,open('movies_dict2.pkl','wb'))

In [287]:
type(movies_dict2)

dict